### ISSUE TITLE
Vorteile der Anonymisierung gegenüber einer Simulierung

### ISSUE THREAD

**Issue by HannesWuensche** [FDZ-Gesundheit/Public-Use-File#1]
Liebes FDZ-Gesundheit,

vielen Dank für das Repository und die bereitgestellten Informationen. Ich hätte eine Nachfrage zum Verfahren:

Könntet ihr noch etwas genauer beschreiben, wieso der Aufwand betrieben wird den Datensatz so aufwendig zu anonymisieren? 
Wäre es nicht einfacher und sicherer einen, dem Datenmodell entsprechenden, simulierten, also völlig fiktiven, Datensatz zu erzeugen? 
Wenn das Ziel ist, die Entwicklung von Code zu ermögliche würde ein simulierter Datensatz eventuell ausreichen. Welcher Vorteil liegt in dem angewendeten Verfahren gegenüber einem simulierten Datensatz?

Ich frage auch nach, weil wir für das Zentrum für Krebsregisterdaten | ZfKD am RKI den Weg gegangen sind, simulierte Beispieldaten bereitzustellen: 

> https://github.com/robert-koch-institut/Bundesweiter_klinischer_Krebsregisterdatensatz-Datenschema_und_Klassifikationen?tab=readme-ov-file#beispieldaten

Es wäre spannend zu erfahren, was wir auf unserem Weg vielleicht nicht bedacht haben. 

Beste Grüße
@hanneswuensche

**Comment by cbrachemfdz** [comment]
Lieber @HannesWuensche,

vielen Dank für deine Nachfrage und dein Interesse!

Wir haben uns für den zusätzlichen Aufwand der Anonymisierung entschieden, da wir in der Vergangenheit eher schlechte Erfahrungen mit einem komplett simuliertem Datensatz gemacht haben. 
Speziell sind in unseren Daten einige unerwartete Fehler und Unstimmigkeiten enthalten, die aus der Dokumentations- und Abrechnungsrealität, für die unsere Daten erhoben werden, stammen. Genau diese Fehler sind in unserer Erfahrung häufige Fehlerquellen in der Skriptentwicklung. 

Natürlich könnte man auch in komplett simulierten Daten die Fehler annähern, um eine "gute Fehlerqualität" zu erzeugen. Dieses Vorgehen erfordert jedoch ungleich mehr Aufwand und ist außerdem nicht gewappnet, um sehr spezifische Sonderfälle abzubilden, die nur bei wenigen Forschungsfragen relevant und deswegen ggf. nicht im Vorfeld bedacht werden können.

Den Vorteil von komplett simulierten Daten kann man aber natürlich nicht von der Hand weisen. Genau aus diesem Grund haben wir als Teil dieses Repositories mit [`generate_test_data.ipynb`](https://github.com/FDZ-Gesundheit/Public-Use-File/blob/main/generate_test_data.ipynb) eine Möglichkeit eingeschlossen, einen komplett simulierten Datensatz als Testdaten zu erzeugen. 

Viele Grüße in Vertretung für das Team
@cbrachemfdz & @lkuehnelfdz

**Comment by HannesWuensche** [comment]
Hallo @cbrachemfdz und @lkuehnelfdz,

vielen Dank für die schnelle Antwort.

Mit dem Wissen ist über die Woche bei uns im Open Data Team der Gedanke gereift, den Ansatz zu übernehmen und als Konzept für weitere offene Datensatzbeschreibungen verwenden zu wollen.

Dafür ist eine genauere Evaluation des Verfahrens, insbesondere aus Datenschutzsicht, nötig. Wenn wir diesbezüglich in einen engeren Austausch treten könnten, würde uns das sehr freuen. So ist es eventuell möglich, den Freigabeprozess für das Verfahren am RKI etwas abzukürzen.

Beste Grüße
@HannesWuensche | OpenData@rki.de
