### ISSUE TITLE
README.md: Logikfehler in puf_erstellung.png, Grammar und Typos

### ISSUE THREAD

**Issue by Lerajaro** [FDZ-Gesundheit/Public-Use-File#2]
Line 5:  So können Skripte schon vor oder während der Antragstellung entwickelt werden um die Gesamtdauer des Forschungsvorhabens deutlich zu verkürzen werden. --> So können Skripte schon vor, oder während der Antragstellung entwickelt werden, um so die Gesamtdauer des Forschungsvorhabens deutlich zu verkürzen.

Line 14: Aufläsung --> Auflösung

Line 20: puf_erstellung.png: Wenn ich die Logik korrekt verstehe sollte nach dem Verarbeitungsschritt "Simple Random Sample 1%" das Produkt nicht erneut "Vollständiger PUF Datensatz" heissen, sondern z.B. "PUF Datensatz 1%-Sample" o.ä..

**Comment by cbrachemfdz** [comment]
Vielen Dank für die Kommentare, alle wie Vorgeschlagen eingearbeitet.
