### ISSUE TITLE
README.md Verschiedene Schreibfehler

### ISSUE THREAD

**Issue by Jolly5** [FDZ-Gesundheit/Public-Use-File#5]
Mir sind einige Fehler (und unschöne Formulierungen) aufgefallen, als ich die README des Projekts gelesen habe. Ich habe einen entsprechenden [Pull Request](/FDZ-Gesundheit/Public-Use-File/pull/4) erstellt, in dem ich alle Fehler behebe, die mir aufgefallen sind.

**Comment by cbrachemfdz** [comment]
Vielen Dank für das Feedback und den Pullrequest! Wir haben die Änderungen vollständig übernommen.
