### ISSUE TITLE
Datenmodell 3

### ISSUE THREAD

**Issue by edg-stg** [FDZ-Gesundheit/Public-Use-File#8]
Hallo liebes FDZ-Team,

vielen Dank für eure Arbeit und die nachvollziehbare Dokumentation zur Erstellung des PUF!

Das Repo ließ sich problemlos klonen und die Skripte liefen anstandslos lokal durch (Ubuntu mit conda).

Für unsere Forschung wäre fast ausschließlich das Datenmodell 3 relevant. Wann wird das Repo um die PUF-Methodik zum Datenmodell 3 ergänzt?

Viele Grüße aus Berlin vom Zi (Zentralinstitut kassenärztliche Versorgung)

**Comment by lkuehnelfdz** [comment]
Hallo @edg-stg,
 
vielen Dank für die positive Rückmeldung. Es freut uns zu hören, dass alle Skripte funktionieren. 
Wir arbeiten aktuell an der Umsetzung für Datenmodell 3, welches deutlich komplexer ist als die vorherigen Datenmodelle. Einen genauen Zeitpunkt können wir Ihnen nicht nennen. Wir tun aber unser Bestes und werden auf verschiedenen Kanälen - z.B. via [LinkedIn](https://www.linkedin.com/company/forschungsdatenzentrum-gesundheit/) - darüber informieren. 

Viele Grüße vom FDZ

**Comment by edg-stg** [comment]
Hallo liebes FDZ-Team,
ich verstehe nicht, warum der Issue als "completed" geschlossen wurde, da der Issue ja eben nicht abgeschlossen wurde (erst mit der Bereitstellung des Datenmodells 3 wäre er erledigt). Aus Gründen der Transparenz sollte der Issue offen bleiben.
Viele Grüße, Edgar Steiger

**Comment by cbrachemfdz** [comment]
Mit #12 erfolgt.
