### ISSUE TITLE
k-Anonymität mit Kategorie "Other": problematisch wegen ICD-10-Kapitel "O" (Schwangerschaft)

### ISSUE THREAD

**Issue by edg-stg** [FDZ-Gesundheit/Public-Use-File#9]
https://github.com/FDZ-Gesundheit/Public-Use-File/blob/2efbfba73ce812349c7a523b3caf99a105e3aef5/functions.py#L102

Eine Standard-Auswertung bei ICD-10-basierten Analysen besteht darin, nach bestimmten ICD-Kapiteln zu filtern/aggregieren, wobei oft einfach der erste Buchstabe der Diagnose-Codes extrahiert wird. Wenn bei der k-Anonymisierung der Wert "Other" für seltene Codes benutzt wird, könnte das bei dieser Analyse Probleme verursachen, da die Codes des ICD-10-Kapitel XV (Schwangerschaft, Geburt, Wochenbett) eben mit "O" beginnen.

Eventuell wäre ein anderer Wert sinnvoll. Ideen (unterschiedliche Vor- und Nachteile):

- "999"
- leeres Feld, NULL oder NA-Value
- Sonderzeichen wie "*" oder "-"
- Verkürzung des seltenen Codes auf nur den Anfangsbuchstaben
- häufigster Code mit demselben Anfangsbuchstaben
- für alle statt "Other" ein valider Code, der aber in der ICD-10-GM nicht vorkommt, zB U000

**Comment by cbrachemfdz** [comment]
Hallo @edg-stg , 
vielen Dank für Ihre Anmerkung!
 
Wir sehen im Kontext des Public Use Files eine Abwägung zwischen zwei Zielen. Auf der einen Seite steht das Problem, wie Sie es beschrieben haben, dass bei Auswertungen mit dem Public Use File die Gruppe "Other" zu Fehlern in der Auswertung führen kann. Auf der anderen Seite möchten wir sehr explizit darin sein, welche Änderungen wir vorgenommen haben. Niemand erwartet den ICD-Code "Other", wenn also Fehler wegen diesem Wert auftreten, kann man eine entsprechende Ausnahme machen, da klar ist, dass hier ein PUF-spezifischer Wert vorliegt.  
"Fehler" in Anführungszeichen, da Ihre Erläuterung natürlich korrekt ist. Das Kapitel "O" würde in der Auswertung mit dem PUF häufiger als erwartet auftauchen. Wir sehen hier aber kein großes Problem, da die Ergebnisse von Auswertung auf dem PUF keinen inhaltlichen Wert haben. Das Public Use File kann ausschließlich zur Entwicklung von Analysecode verwendet werden. Dabei sollte es keinen Unterschied für die Codeentwicklung machen, ob die Codes im Kapitel "O" scheinbar zu häufig vorkommen.
 
Wir haben uns deswegen hier bewusst für die explizite Information "Hier steht eigentlich etwas anderes" entschieden.
